---
deployment:
  tasks:
    - export DEPLOYPATH=/home/solarisroofs/promo.solarisroofs.com/
    - cd $REPO
    - /bin/npm install
    - /bin/npm run build
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R $REPO/build/* $DEPLOYPATH
