deployment:
  tasks:
    - export NODE_ENV=production
    - cd $REPO && npm install
    - cd $REPO && npm run build
    - rm -rf /home/solarisroofs/promo.solarisroofs.com/*
    - cp -r $REPO/build/* /home/solarisroofs/promo.solarisroofs.com/
